// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP6XOEfQ7sC5R0SLaQpP3lVzmfgwQBYKM',
    appId: '1:560091932094:web:2568fc54fd90fe5a37c5ef',
    messagingSenderId: '560091932094',
    projectId: 'congdduck-fe288',
    authDomain: 'congdduck-fe288.firebaseapp.com',
    storageBucket: 'congdduck-fe288.firebasestorage.app',
    measurementId: 'G-ET87S6569T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9u1ukt6l8LAaUK5SiZt-MNls3r_OvOjU',
    appId: '1:560091932094:android:403bfe7de7cee5c037c5ef',
    messagingSenderId: '560091932094',
    projectId: 'congdduck-fe288',
    storageBucket: 'congdduck-fe288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3FZQN3sgcvrWvztkAcJMzPKqy561n9TI',
    appId: '1:560091932094:ios:4c70b35f7add3dc737c5ef',
    messagingSenderId: '560091932094',
    projectId: 'congdduck-fe288',
    storageBucket: 'congdduck-fe288.firebasestorage.app',
    iosBundleId: 'com.example.congdduck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3FZQN3sgcvrWvztkAcJMzPKqy561n9TI',
    appId: '1:560091932094:ios:4c70b35f7add3dc737c5ef',
    messagingSenderId: '560091932094',
    projectId: 'congdduck-fe288',
    storageBucket: 'congdduck-fe288.firebasestorage.app',
    iosBundleId: 'com.example.congdduck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP6XOEfQ7sC5R0SLaQpP3lVzmfgwQBYKM',
    appId: '1:560091932094:web:26881ccb90d4e89b37c5ef',
    messagingSenderId: '560091932094',
    projectId: 'congdduck-fe288',
    authDomain: 'congdduck-fe288.firebaseapp.com',
    storageBucket: 'congdduck-fe288.firebasestorage.app',
    measurementId: 'G-61TFBDVBN9',
  );
}
